import Vue from 'vue'
import Vuetify from 'vuetify/lib/framework'
import {
  mdiArrowRightDropCircle,
  mdiVolumeOff,
  mdiVolumeMute,
  mdiVolumeHigh,
  mdiPlusCircle,
  mdiViewDashboardOutline,
  mdiCogOutline,
  mdiFormatListChecks,
  mdiLaptop,
  mdiCoffeeOutline,
  mdiRotate3dVariant,
  mdiPauseCircle,
  mdiArrowLeft,
  mdiContentSaveOutline,
  mdiArrowUp,
  mdiCheckCircleOutline,
  mdiFileImage,
  mdiPaperclip,
  mdiCheckboxBlankOutline,
  mdiCheckboxMarked,
  mdiChevronDown,
  mdiArchiveCheckOutline,
  mdiMenuDown,
  mdiCropSquare,
  mdiChartBoxOutline,
  mdiChevronLeft,
  mdiChevronRight,
  mdiCalendar,
  mdiHomeOutline,
  mdiRadioboxBlank,
  mdiRadioboxMarked,
  mdiTimerPauseOutline,
  mdiMenu,
  mdiCloseThick,
  mdiBackupRestore,
  mdiFileRestoreOutline,
  mdiRestore,
  mdiDeleteOutline,
  mdiCloudUploadOutline,
  mdiHelpCircleOutline,
  mdiCloseCircleOutline,
  mdiVolumeMedium
} from '@mdi/js'

Vue.use(Vuetify)

export default new Vuetify({
  theme: {dark: false},
  icons: {
    iconfont: 'mdi',
    values: {
      'mdi-volume-off': mdiVolumeOff,
      'mdi-volume-mute': mdiVolumeMute,
      'mdi-volume-low': mdiVolumeMedium,
      'mdi-volume-high': mdiVolumeHigh,
      'mdi-plus-circle': mdiPlusCircle,
      'mdi-view-dashboard-outline': mdiViewDashboardOutline,
      'mdi-cog-outline': mdiCogOutline,
      'mdi-format-list-checks': mdiFormatListChecks,
      'mdi-laptop': mdiLaptop,
      'mdi-coffee-outline': mdiCoffeeOutline,
      'mdi-rotate-3d-variant': mdiRotate3dVariant,
      'mdi-pause-circle': mdiPauseCircle,
      'mdi-arrow-right-drop-circle': mdiArrowRightDropCircle,
      'mdi-crop-square': mdiCropSquare,
      'mdi-arrow-left': mdiArrowLeft,
      'mdi-content-save-outline': mdiContentSaveOutline,
      'mdi-arrow-up': mdiArrowUp,
      'mdi-check-circle-outline': mdiCheckCircleOutline,
      'mdi-file-image': mdiFileImage,
      'mdi-close-box-multiple': mdiArchiveCheckOutline,
      'mdi-chart-box-outline': mdiChartBoxOutline,
      'mdi-chevron-left': mdiChevronLeft,
      'mdi-chevron-right': mdiChevronRight,
      'mdi-calendar': mdiCalendar,
      'mdi-home-outline': mdiHomeOutline,
      'mdi-timer-pause-outline': mdiTimerPauseOutline,
      'mdi-close-thick': mdiCloseThick,
      'mdi-cloud-upload-outline': mdiCloudUploadOutline,
      'mdi-backup-restore': mdiBackupRestore,
      'mdi-file-restore-outline': mdiFileRestoreOutline,
      'mdi-restore': mdiRestore,
      'mdi-delete-outline': mdiDeleteOutline,
      'mdi-help-circle-outline': mdiHelpCircleOutline,
      'mdi-close-circle-outline': mdiCloseCircleOutline,
      menu: mdiMenu,
      checkboxOn: mdiCheckboxMarked,
      checkboxOff: mdiCheckboxBlankOutline,
      file: mdiPaperclip,
      expand: mdiChevronDown,
      dropdown: mdiMenuDown,
      prev: mdiChevronLeft,
      next: mdiChevronRight,
      radioOff: mdiRadioboxBlank,
      radioOn: mdiRadioboxMarked
    }
  }
})
